2021-10-06 22:11:56 INFO: Created <Thread(t_update_2, initial)>: SE7K solaredge-inverter Inverter(solaredge.fritz.box:502, connectionType.TCP: timeout=1, retries=3, unit=0x2)
2021-10-06 22:11:57 INFO: Starting <Thread(t_update_2, started 3052381248)>
2021-10-06 22:11:58 ERROR: Connection to (solaredge.fritz.box, 502) failed: timed out
2021-10-06 22:11:59 ERROR: Connection to (solaredge.fritz.box, 502) failed: timed out
2021-10-06 22:12:00 ERROR: Connection to (solaredge.fritz.box, 502) failed: timed out
2021-10-06 22:12:01 ERROR: Connection to (solaredge.fritz.box, 502) failed: timed out
2021-10-06 22:12:02 ERROR: Connection to (solaredge.fritz.box, 502) failed: timed out
2021-10-06 22:12:03 ERROR: Connection to (solaredge.fritz.box, 502) failed: timed out
2021-10-06 22:12:04 ERROR: Connection to (solaredge.fritz.box, 502) failed: timed out
2021-10-06 22:12:06 ERROR: Connection to (solaredge.fritz.box, 502) failed: timed out
2021-10-06 22:28:11 INFO: Created <Thread(t_update_2, initial)>: SE7K solaredge-inverter Inverter(solaredge.fritz.box:502, connectionType.TCP: timeout=1, retries=3, unit=0x2)
2021-10-06 22:28:12 INFO: Starting <Thread(t_update_2, started 3052000320)>
2021-10-06 22:28:12 ERROR: Connection to (solaredge.fritz.box, 502) failed: [Errno 111] Connection refused
Traceback (most recent call last):
  File "SE7K-proxy-tcp.py", line 353, in <module>
    confparser["server"].getint("port", fallback=default_config["server"]["port"])
  File "/usr/local/lib/python3.7/dist-packages/pymodbus-2.5.3rc1-py3.7.egg/pymodbus/server/sync.py", line 620, in StartTcpServer
    server = ModbusTcpServer(context, framer, identity, address, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymodbus-2.5.3rc1-py3.7.egg/pymodbus/server/sync.py", line 340, in __init__
    **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
2021-10-06 22:30:21 INFO: Created <Thread(t_update_2, initial)>: SE7K solaredge-inverter Inverter(solaredge.fritz.box:502, connectionType.TCP: timeout=1, retries=3, unit=0x2)
2021-10-06 22:30:22 INFO: Starting <Thread(t_update_2, started 3051643968)>
Traceback (most recent call last):
  File "SE7K-proxy-tcp.py", line 353, in <module>
    confparser["server"].getint("port", fallback=default_config["server"]["port"])
  File "/usr/local/lib/python3.7/dist-packages/pymodbus-2.5.3rc1-py3.7.egg/pymodbus/server/sync.py", line 620, in StartTcpServer
    server = ModbusTcpServer(context, framer, identity, address, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/pymodbus-2.5.3rc1-py3.7.egg/pymodbus/server/sync.py", line 340, in __init__
    **kwargs)
  File "/usr/lib/python3.7/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.7/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
PermissionError: [Errno 13] Permission denied
2021-10-06 22:31:52 INFO: Created <Thread(t_update_2, initial)>: SE7K solaredge-inverter Inverter(solaredge.fritz.box:502, connectionType.TCP: timeout=1, retries=3, unit=0x2)
2021-10-06 22:31:53 INFO: Starting <Thread(t_update_2, started 3052024896)>
2021-10-06 22:34:29 INFO: Created <Thread(t_update_2, initial)>: SE7K solaredge-inverter Inverter(solaredge.fritz.box:502, connectionType.TCP: timeout=1, retries=3, unit=0x2)
2021-10-06 22:34:30 INFO: Starting <Thread(t_update_2, started 3052028992)>
